# -*-python-*-
from openalea.sconsx.config import platform

Import( "env" )

# 1. Call other SConscript files in sub directories
lib_env = env.Copy()

includes= lib_env.ALEAGlob('*.h')
lib_env.ALEAIncludes( "plantgl/gui", includes )

# install headers

SConscript( 'base/SConscript', exports = { "env" : lib_env, 
                                           "platform" : platform } )
SConscript( 'viewer/SConscript', exports = { "env" : lib_env } )

# Select recursively the sources
sources= []

for d in ['base','viewer']:
    sources+= lib_env.ALEAGlob('*.cpp', dir= d)
    if d == 'base' and platform.name != 'win32':
        sources= filter( lambda x: 'trayicon' not in x, sources )

    sources+= lib_env.ALEAGlob('*.ui',dir=d+'/interface')

# Add defines to export symbols on Windows
DEFINES= list(lib_env['CPPDEFINES'])
DEFINES.append('VIEW_MAKEDLL')

# Link with the following libraries
LIBRARIES = list( lib_env['LIBS'] )
LIBRARIES.extend( ['pgltool','pglmath','pglsg','pglalgo'] )

lib_env.ALEALibrary( "pglgui",
                     sources, 
                     CPPDEFINES = DEFINES, 
                     LIBS = LIBRARIES )

# Build the viewer program
SConscript( 'exe/SConscript', exports = { "env" : lib_env } )

