# -*-python-*-
import os
pj= os.path.join

Import( "env" )

# 1. Call other SConscript files in sub directories and build the library

lib_env= env.Copy()

includes= lib_env.ALEAGlob('*.h')
lib_env.ALEAIncludes( "plantgl/algo", includes )

dirs= Split("""
base
fitting
opengl
""")

# install headers
#lib_env.SConscript( dirs, exports = { "env" : lib_env } )

# sources
sources= lib_env.ALEAGlob('*.cpp', dir = '*')
print sources
#sources= []
#for d in dirs:
#    src= lib_env.SConscript( d, exports = { "env" : lib_env } )
#    if src: sources+= src

# print sources
# Add defines to export symbols on Windows
DEFINES= list(lib_env['CPPDEFINES'])
DEFINES.append('ALGO_MAKEDLL')

# Link with the following libraries
LIBRARIES = list( lib_env['LIBS'] )
LIBRARIES.extend( ['pgltool','pglmath','pglsg'] )

lib_env.ALEALibrary( "pglalgo",
                     sources, 
                     CPPDEFINES = DEFINES, 
                     LIBS = LIBRARIES )


