# -*-python-*-

Import( "env" )


py_dir = '../../plantgl/scenegraph'

# Build wrappers as shared libraries
lib_env=env.Copy()
qt_version = int(env['QT_VERSION'])
if qt_version == 4:
    lib_env.EnableQt4Modules( [ 'QtCore' ])
    lib_env.AppendUnique( CPPPATH = ['$QT4_CPPPATH/Qt'] )

sources= lib_env.ALEAGlob( '*.cpp' )
target= "_pglsg"

lib_env.AppendUnique(LIBS= ['pglmath','pglsg','pglalgo','pgltool'])
lib_env.ALEAWrapper( py_dir, target, sources )

