# -*-python-*-
import os.path
pj = os.path.join

Import( "env" )
lib_env = env.Copy()

# 1. Select and install the headers

includes= lib_env.ALEAGlob('*.h')
lib_env.ALEAIncludes( pj('plantgl','python'), includes )

