# -*-python-*-
import os, re
from glob import glob

pj= os.path.join

Import( "env" )

# 1. Select the headers and sources

local_dir = str(env.Dir( "." ).srcnode())

h_files= pj(local_dir,'*.h')
includes= glob(h_files)

cpp_files= pj(local_dir,'*.cpp')
sources= glob(cpp_files)

# 2. Build and install the library/headers

lib_env = env.Copy()
inc= lib_env.ALEAIncludes( "plantgl/tool", includes )
lib = lib_env.ALEALibrary( "pgltool", sources )
