# -*-python-*-
Import( "env" )

# 1. Select the headers and sources

lib_env = env.Copy()

includes= lib_env.ALEAGlob('*.h')
sources= lib_env.ALEAGlob('*.cpp')

# Add defines to export symbols on Windows
DEFINES= list(lib_env['CPPDEFINES'])
DEFINES.append('TOOLS_MAKEDLL')

inc= lib_env.ALEAIncludes( "plantgl/tool", includes )

lib = lib_env.ALEALibrary( "pgltool", 
                           sources, 
                           CPPDEFINES = DEFINES )
