# -*-python-*-
import os
from glob import glob

pj= os.path.join

Import( "env" )

# 1. Select and install the headers

local_dir = str(env.Dir( "." ).srcnode())
h_files= pj(local_dir,'*.h')
includes= glob(h_files)

cpp_files= pj(local_dir,'*.cpp')
sources= glob(cpp_files)

# 2. Build PlantGL math library

lib_env = env.Copy()

# Add defines to export symbols on Windows
DEFINES= list(lib_env['CPPDEFINES'])
DEFINES.append('PGLMATH_MAKEDLL')

inc= lib_env.ALEAIncludes( "plantgl/math", includes )

lib = lib_env.ALEALibrary( "pglmath", 
                           sources,
                           CPPDEFINES = DEFINES )

