# -*-python-*-
import os
from glob import glob

pj= os.path.join

Import( "env" )

# 2. Build PlantGL math library

lib_env = env.Copy()

includes= lib_env.ALEAGlob('*.h')
sources= lib_env.ALEAGlob('*.cpp')

# Add defines to export symbols on Windows
DEFINES= list(lib_env['CPPDEFINES'])
DEFINES.append('PGLMATH_MAKEDLL')

inc= lib_env.ALEAIncludes( "plantgl/math", includes )

lib = lib_env.ALEALibrary( "pglmath", 
                           sources,
                           CPPDEFINES = DEFINES )

