# -*-python-*-
import os, re
from glob import glob

pj= os.path.join

Import( "env" )

# 1. Select and install the headers

includes= env.ALEAGlob('*.h')
sources= env.ALEAGlob('*.cpp')
sources+= env.ALEAGlob('*.ui','./interface')

# 2. Call other SConscript files in sub directories

env.ALEAIncludes( "plantgl/gui/base", includes )

Return( 'sources' )

