# -*-python-*-
Import( "env" )

lib_env= env.Copy()

includes= lib_env.ALEAGlob('*.h')
lib_env.ALEAIncludes( "plantgl/scenegraph", includes )

dirs=lib_env.ALEAGlob('SConscript','*') 

# Install headers
SConscript( dirs, exports = { "env" : lib_env } )

# Select recursively the sources
sources= lib_env.ALEAGlob('*.cpp','*')
sources+= lib_env.ALEAGlob('*.cpp')

# Add defines to export symbols on Windows
DEFINES= list(lib_env['CPPDEFINES'])
DEFINES.append('SG_MAKEDLL')

# Link with the following libraries
LIBRARIES= list(lib_env['LIBS'])
LIBRARIES.extend(['pgltool','pglmath'])

lib_env.ALEALibrary( "pglsg",
                     sources, 
                     CPPDEFINES = DEFINES, 
                     LIBS = LIBRARIES )

