# -*-python-*-
Import( "env" )

lib_env= env.Copy()

qt_version = float(lib_env['QT_VERSION'])
if qt_version == 4:
    lib_env.EnableQt4Modules( [ 'QtCore' ])

includes= lib_env.ALEAGlob('*.h')
lib_env.ALEAIncludes( "plantgl/scenegraph", includes )

dirs=lib_env.ALEAGlob('SConscript','*') 

# Install headers
SConscript( dirs, exports = { "env" : lib_env } )

# Select recursively the sources
sources= lib_env.ALEAGlob('*.cpp','*')
sources+= lib_env.ALEAGlob('*.cpp')

# Add defines to export symbols on Windows
# DEFINES= list(lib_env['CPPDEFINES'])
# DEFINES.append('SG_MAKEDLL')
lib_env.AppendUnique( CPPDEFINES = [ 'SG_MAKEDLL' ] )

# Link with the following libraries
#LIBRARIES= list(lib_env['LIBS'])
#LIBRARIES.extend(['pgltool','pglmath'])
lib_env.AppendUnique( LIBS = [ 'pgltool', 'pglmath'] )

lib_env.ALEALibrary( "pglsg",
                     sources 
                     )

