# -*-python-*-
Import( "env" )

lib_env = env.Clone()
qt_version = int(lib_env['QT_VERSION'])
lib_env.EnableQtModules( [ 'QtCore'])

includes= lib_env.ALEAGlob('*.h')
sources= lib_env.ALEAGlob('*.cpp')

# Add defines to export symbols on Windows
DEFINES= list(lib_env['CPPDEFINES'])
DEFINES.append('TOOLS_MAKEDLL')

import os
if os.name != 'posix':
	lib_env.AppendUnique(LIBS = 'Advapi32')

inc= lib_env.ALEAIncludes( "plantgl/tool", includes )

lib = lib_env.ALEALibrary( "pgltool", 
                           sources, 
                           CPPDEFINES = DEFINES,
                           CPPPATH = lib_env['CPPPATH'],
                            )
