# -*-python-*-
Import( "env" )

lib_env = env.Clone()

qt_version = eval(lib_env['QT_VERSION'])
if not qt_version is None:
    lib_env.EnableQtModules( [ 'QtCore'])

includes= lib_env.ALEAGlob('*.h')
sources= lib_env.ALEAGlob('*.cpp')

# Add defines to export symbols on Windows
DEFINES= list(lib_env['CPPDEFINES'])
DEFINES.append('TOOLS_MAKEDLL')

import os, sys
if os.name != 'posix':
    if  sys.maxsize.bit_length() < 63
        lib_env.AppendUnique(LIBS = 'Advapi32')
    else:
        lib_env.AppendUnique(LIBS = 'Advapi64')

inc= lib_env.ALEAIncludes( "plantgl/tool", includes )

lib = lib_env.ALEALibrary( "pgltool", 
                           sources, 
                           CPPDEFINES = DEFINES,
                           CPPPATH = lib_env['CPPPATH'],
                            )
