# -*-python-*-

import os
from openalea.sconsx.config import *

pj= os.path.join

Import( "env" )

exe_env= env.Copy()
exe_env.EnableQt4Modules([ 'Qt3Support', 'QtOpenGL', 'QtCore', 'QtGui' ])

source= ["mainviewer.cpp"]

LIBRARIES = list( exe_env['LIBS'] )
LIBRARIES.extend( ['pglgui', 'pglalgo', 'pgltool', 'pglmath','pglsg', 'qtmain'] )

exe_env.Append( CPPPATH = '#/share/plantgl/pixmap')

if isinstance( platform, Win32 ):
    res=exe_env.RES('icon.rc')
    source.append(res)

exe_env.ALEAProgram( "pglviewer", source, LIBS = LIBRARIES )


