# -*-python-*-

import os
pj= os.path.join

Import( "env" )

source= ["mainviewer.cpp"]

LIBRARIES = list( env['LIBS'] )
LIBRARIES.extend( ['pglgui'] )

env.ALEAProgram( "viewer", source, LIBS = LIBRARIES )


