# -*-python-*-

import os
pj= os.path.join

Import( "env" )

exe_env= env.Copy()

source= ["mainviewer.cpp"]

LIBRARIES = list( exe_env['LIBS'] )
LIBRARIES.extend( ['pglgui', 'pglalgo', 'pgltool', 'pglmath','pglsg'] )

exe_env.Append( CPPPATH = '#/share/plantgl/pixmap')
res=exe_env.RES('icon.rc')
source.append(res)
exe_env.ALEAProgram( "pglviewer", source, LIBS = LIBRARIES )


