# -*-python-*-

Import( "env" )
import os 
pj = os.path.join


subdirs = ['math','scenegraph','algo']
if not eval(env['QT_VERSION']) is None:
	subdirs += ['gui']

subdirs = [ pj(i,'SConscript') for i in subdirs]
print(subdirs)

SConscript( subdirs, exports= { 'env' : env } )



