# -*-python-*-

Import( "env" )
import os 
pj = os.path.join

# 1. Select and install the headers

includes= env.ALEAGlob('*.h',dir='util')
env.ALEAIncludes( pj('plantgl','wrapper'), includes )

# 2. Call other SConscript files in sub directories
#dirs= env.ALEAGlob( 'SConscript' , dir='*')
subdirs = ['math','scenegraph','algo']
qt_version = int(env['QT_VERSION'])
if qt_version == 4:
    subdirs.append('gui')
else:
    subdirs.append('gui3')
subdirs = [ pj(i,'SConscript') for i in subdirs]
#print(subdirs)

SConscript( subdirs, exports= { 'env' : env } )



