package:
  name: vplants.plantgl
  version: 2.21.1

source:
  path: ..


about:
  home: http://openalea.gforge.inria.fr
  license: GPL/LGPL
  summary: An open-source graphic toolkit for the creation, simulation and analysis of 3D virtual plants.

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
   - python
   #- m4
   - setuptools
   - openalea.deploy
   - scons
   - openalea.sconsx
   - qt <5
   - boost
   - bison [unix]
   - flex 2.5.39 [unix]
   - m2-bison [win]
   - m2-flex  [win]
   - cgal
   - gmp [unix]
   - eigen
   - ann
   - qhull
   - patchelf [linux]
  run:
   - python
   - openalea.deploy
   - openalea.core
   - qt <5
   - pyqt
   - gmp [unix]
   - cgal
   - qhull
   - ann
   - boost
   - path.py

test:
  requires:
    - nose
  imports:
    - openalea.plantgl
  source_files:
    - test/test_*.py
    - test/data
    - share/
  commands:
   - nosetests -v -I test_viewer.py -I test_projpershape.py -I thread.py -I test_geomprinter.py -I test_coneofperception.py -I test_pointgrid.py # -I test_bbox.py -I test_codec.py  
