# -*-python-*-
Import( "env" )

# 1. Select and install the headers

includes= env.ALEAGlob('*.h')

env.ALEAIncludes( "plantgl", includes )

# 2. Call other SConscript files in sub directories
dirs= env.ALEAGlob( 'SConscript' , dir='*')

SConscript( dirs, exports= { 'env' : env } )

