# -*-python-*-
Import( "env" )
import os 
pj = os.path.join

# 1. Select and install the headers

includes= env.ALEAGlob('*.h')
env.ALEAIncludes( "plantgl", includes )

# 2. Call other SConscript files in sub directories
#dirs= env.ALEAGlob( 'SConscript' , dir='*')
subdirs = ['tool','math','scenegraph','algo','gui']
subdirs = [ pj(i,'SConscript') for i in subdirs]
#print(subdirs)

SConscript( subdirs, exports= { 'env' : env } )

