# -*-python-*-
Import( "env" )

# 1. Call other SConscript files in sub directories
lib_env = env.Copy()

includes= lib_env.ALEAGlob('*.h')
lib_env.ALEAIncludes( "plantgl/gui", includes )

# install headers

SConscript( 'base/SConscript', exports = { "env" : lib_env } )

# Select recursively the sources
sources= lib_env.ALEAGlob('*.cpp','*')
ui_sources= lib_env.ALEAGlob('*.ui','*/interface')
sources+= ui_sources

for d in dirs:
    src= lib_env.SConscript( d, exports = { "env" : lib_env } )
    if src: 
        d=d.replace('SConscript','')
        sources.extend( map( lambda x: d+x, src ) )

# Add defines to export symbols on Windows
DEFINES= list(lib_env['CPPDEFINES'])
DEFINES.append('VIEW_MAKEDLL')

# Link with the following libraries
LIBRARIES = list( lib_env['LIBS'] )
LIBRARIES.extend( ['pgltool','pglmath','pglsg','pglalgo'] )

lib_env.ALEALibrary( "pglgui",
                     sources, 
                     CPPDEFINES = DEFINES, 
                     LIBS = LIBRARIES )

