# -*-python-*-
import os
pj = os.path.join

Import( "env" )

# 1. Call other SConscript files in sub directories
lib_env = env.Copy()

includes= lib_env.ALEAGlob('*.h')
lib_env.ALEAIncludes( "plantgl/gui", includes )

# dirs = [d for d in glob('*') if os.path.isdir(d)]
sub_dirs= lib_env.ALEAGlob('*')
dirs = [ pj ( os.path.basename(d),'SConscript' )
         for d in sub_dirs if os.path.isdir(d) ]

sources = []

for d in dirs:
    src= lib_env.SConscript( d, exports = { "env" : lib_env } )
    if src: 
        d=d.replace('SConscript','')
        sources.extend( map( lambda x: d+x, src ) )

# Add defines to export symbols on Windows
DEFINES= list(lib_env['CPPDEFINES'])
DEFINES.append('VIEW_MAKEDLL')

# Link with the following libraries
LIBRARIES = list( lib_env['LIBS'] )
LIBRARIES.extend( ['pgltool','pglmath','pglsg','pglalgo'] )

lib_env.ALEALibrary( "pglgui",
                     sources, 
                     CPPDEFINES = DEFINES, 
                     LIBS = LIBRARIES )

