 # -Appearance File-
(# --------------------------------------------------
 #  
 #  File : /home/fboudon/PovRay/Test/basis.app
 #  
 #  File Author : fboudon
 #  Date : 10/9/2001 at 17:25:48
 #  
 #  This file was generated by the Geom 3D Viewer.
 #  Published under the GNU General Public Licence. 
 #  
 # --------------------------------------------------
 #)

Material Default { 
}

