# -*-python-*-

Import( "env" )

py_dir = '../../plantgl/algo'

# Build wrappers as shared libraries
lib_env=env.Copy()

sources= lib_env.ALEAGlob( '*.cpp' )
target= "_pglalgo"

lib_env.AppendUnique(LIBS= ['pglmath','pgltool','pglsg','pglalgo'])
lib_env.ALEAWrapper( py_dir, target, sources )

