# -*-python-*-

Import( "env" )

py_dir = '../../plantgl/math'

# Build wrappers as shared libraries
lib_env=env.Clone()

sources= lib_env.ALEAGlob( '*.cpp' )
target= "_pglmath"

lib_env.AppendUnique(LIBS= ['pglmath'])
lib_env.ALEAWrapper( py_dir, target, sources )

print 'Ask creation of '+repr(target)+' with '+str(sources)