

# --- Config Header File

function(init_cpp_config CONFIG_CPPFILE)
    set(CONFIG_CPPFILE ${CONFIG_CPPFILE} PARENT_SCOPE)
    file(WRITE ${CONFIG_CPPFILE} "// User configuration of the PlantGL project.\n")
    file(APPEND ${CONFIG_CPPFILE} "// This file is automatically generated. Do not edit it directly.\n")
    string(TIMESTAMP TODAY)
    file(APPEND ${CONFIG_CPPFILE} "// Generated on ${TODAY}.\n")
endfunction()

function(init_py_config CONFIG_PYFILE)
    set(CONFIG_PYFILE ${CONFIG_PYFILE}  PARENT_SCOPE)
    file(WRITE ${CONFIG_PYFILE} "# User configuration of the PlantGL project.\n")
    file(APPEND ${CONFIG_PYFILE} "# This file is automatically generated. Do not edit it directly.\n")
    string(TIMESTAMP TODAY)
    file(APPEND ${CONFIG_PYFILE} "# Generated on ${TODAY}.\n")
endfunction()

# --- Define a Preprocessor Macro

macro(define_cpp_macro DEF_NAME DEF_VALUE)
    # Preprocessor
    add_compile_definitions("${DEF_NAME}=${DEF_VALUE}")
    
    # Append to Header File
    file(APPEND ${CONFIG_CPPFILE} "\n#define ${DEF_NAME} ${DEF_VALUE}\n")
endmacro()

macro(define_py_macro DEF_NAME DEF_VALUE)
    # Append to Python File
    file(APPEND ${CONFIG_PYFILE} "\n${DEF_NAME} = ${DEF_VALUE}\n")
endmacro()

function(define_macro DEF_NAME DEF_VALUE)
    define_cpp_macro(${DEF_NAME} ${DEF_VALUE})
    define_py_macro(${DEF_NAME} ${DEF_VALUE})
endfunction()
