# -*-python-*-

Import( "env" )

py_dir = '../../plantgl/gui'

# Build wrappers as shared libraries
lib_env=env.Copy()

sources= lib_env.ALEAGlob( '*.cpp' )
target= "_pglgui"

lib_env.AppendUnique(LIBS= ['pglmath','pglgui'])
lib_env.ALEAWrapper( py_dir, target, sources )

