# -*-python-*-

Import( "env" )

py_dir = '../../plantgl/gui'

# Build wrappers as shared libraries
lib_env=env.Clone()
lib_env.EnableQt4Modules( [ 'QtCore', 'QtGui', 'QtOpenGL', 'Qt3Support', 'QtNetwork'])
lib_env.AppendUnique( CPPPATH = ['$QT4_CPPPATH/Qt'] )

sources= lib_env.ALEAGlob( '*.cpp' )
target= "_pglgui"

lib_env.AppendUnique(LIBS= ['pglmath','pglgui','pglsg','pgltool'])
lib_env.ALEAWrapper( py_dir, target, sources )

