# -*-python-*-

Import( "env" )

py_dir = '../../plantgl/gui'

# Build wrappers as shared libraries
lib_env=env.Clone()


qt_version = int(lib_env['QT_VERSION'])
if qt_version == 4:
    lib_env.EnableQtModules( [ 'QtCore', 'QtGui', 'QtOpenGL', 'QtNetwork'])
else:
    lib_env.EnableQtModules( [ 'QtCore', 'QtGui', 'QtWidgets', 'QtOpenGL', 'QtNetwork'])    

sources= lib_env.ALEAGlob( '*.cpp' )
target= "_pglgui"

lib_env.AppendUnique(LIBS= ['pglmath','pglgui','pglsg','pgltool'])
lib_env.ALEAWrapper( py_dir, target, sources )

