# -*-python-*-

Import( "env" )

lib_env = env.Clone()

includes= lib_env.ALEAGlob('*.h')
sources= lib_env.ALEAGlob('*.cpp')

# Add defines to export symbols on Windows
DEFINES= list(lib_env['CPPDEFINES'])
DEFINES.append('PGLMATH_MAKEDLL')

inc= lib_env.ALEAIncludes( "plantgl/math", includes )

lib = lib_env.ALEALibrary( "pglmath", 
                           sources,
                           CPPDEFINES = DEFINES )

